# Generated by Django 4.1.1 on 2022-10-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primerNombre', models.CharField(max_length=250)),
                ('segundoNombre', models.CharField(max_length=250)),
                ('primerApellido', models.CharField(max_length=250)),
                ('segundoApellido', models.CharField(max_length=250)),
                ('descripción', models.TextField()),
            ],
        ),
    ]
