# Generated by Django 4.1.1 on 2022-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_trabajador_colaboradores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradores',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='foto',
            field=models.ImageField(blank='True', upload_to='servicios'),
        ),
    ]
