# Generated by Django 4.1.1 on 2022-11-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_colaboradores_options_colaboradores_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='primerApellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='primerNombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='segundoApellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='segundoNombre',
            field=models.CharField(max_length=100),
        ),
    ]
