# Generated by Django 4.1.1 on 2022-11-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_colaboradores_primerapellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='foto',
        ),
    ]
