# Generated by Django 4.1.1 on 2022-11-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_descripción_colaboradores_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='descripcion',
            new_name='descripcin',
        ),
    ]
