# Generated by Django 4.1.1 on 2022-11-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_descripcion_colaboradores_descripcin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradores',
            old_name='descripcin',
            new_name='descripcion',
        ),
    ]
