# Generated by Django 4.1.1 on 2022-11-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_descripcin_colaboradores_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='descripcion',
        ),
    ]
