# Generated by Django 4.1.1 on 2022-11-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_colaboradores_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='foto',
            field=models.ImageField(blank='True', upload_to='servicios'),
        ),
    ]
