# Generated by Django 4.1.1 on 2022-11-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_colaboradores_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='primerApellido',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='primerNombre',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='segundoApellido',
        ),
        migrations.RemoveField(
            model_name='colaboradores',
            name='segundoNombre',
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
