# Generated by Django 4.1.1 on 2022-11-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_colaboradores_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='descripcion',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='primerApellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='primerNombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='segundoApellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='segundoNombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
