# Generated by Django 4.1.1 on 2022-11-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_colaboradores_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='foto',
            field=models.ImageField(blank='True', upload_to='servicios'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='primerApellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='primerNombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='segundoApellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='segundoNombre',
            field=models.CharField(max_length=100),
        ),
    ]
