# Generated by Django 4.1.1 on 2022-11-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_colaboradores_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
