# Generated by Django 4.1.1 on 2022-11-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_colaboradores_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
