# Generated by Django 4.1.1 on 2022-11-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_colaboradores_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='primerNombre',
            field=models.CharField(max_length=6),
        ),
    ]
