# Generated by Django 4.1.1 on 2022-11-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_colaboradores_primernombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='primerNombre',
            field=models.CharField(max_length=100),
        ),
    ]
