# Generated by Django 4.1.1 on 2022-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0009_alter_servicios_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Colaborador_categoria_servicio',
        ),
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.TextField(max_length=285),
        ),
    ]
